blank_issues_enabled: true
contact_links:
  - name: Mippscoin Core Security Policy
    url: https://github.com/mippscoin/mippscoin/blob/master/SECURITY.md
    about: View security policy
  - name: Mippscoin Core Developers
    url: https://mippscoincore.org
    about: Mippscoin Core homepage
