.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. mippscoin_qt test_mippscoin_qt
clean: FORCE
	$(MAKE) -C .. mippscoin_qt_clean test_mippscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_mippscoin_qt_check
mippscoin-qt mippscoin-qt.exe: FORCE
	 $(MAKE) -C .. mippscoin_qt
apk: FORCE
	$(MAKE) -C .. mippscoin_qt_apk
